version: '3.8'

services:
  # Apache Airflow
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - airflow-init
    command: webserver
    environment:
      &airflow-common-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
      AIRFLOW__CORE__ENABLE_XCOM_PICKLING: 'true'
      # PySpark and Java environment
      JAVA_HOME: /usr/local/openjdk-17
      SPARK_HOME: /opt/spark
      PYTHONPATH: /opt/airflow/dags:/opt/airflow/plugins
      # Spark job configuration
      STORAGE_BUCKET: spark-data
      CATALOG_TYPE: hadoop
      CATALOG_NAME: spark_catalog
      CATALOG_WAREHOUSE_NAME: iceberg-warehouse
      CATALOG_IO_IMPL: org.apache.iceberg.aws.s3.S3FileIO
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./requirements.txt:/opt/airflow/requirements.txt
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - spark-network

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - airflow-init
    command: scheduler
    environment:
      <<: *airflow-common-env
      # Spark job configuration
      STORAGE_BUCKET: spark-data
      CATALOG_TYPE: hadoop
      CATALOG_NAME: spark_catalog
      CATALOG_WAREHOUSE_NAME: iceberg-warehouse
      CATALOG_IO_IMPL: org.apache.iceberg.aws.s3.S3FileIO
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./requirements.txt:/opt/airflow/requirements.txt
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - spark-network

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - postgres
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-admin}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-admin}
      _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./requirements.txt:/opt/airflow/requirements.txt
    command: >
      bash -c "
        airflow db migrate && \
        airflow users create \
          --role Admin \
          --username ${_AIRFLOW_WWW_USER_USERNAME:-admin} \
          --password ${_AIRFLOW_WWW_USER_PASSWORD:-admin} \
          --email admin@example.com \
          --firstname Admin \
          --lastname User || true
      "
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: on-failure
    networks:
      - spark-network

  # PostgreSQL for Airflow metadata
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - spark-network

  # MinIO for local S3-compatible storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
    networks:
      - spark-network

  # MinIO Client for setup (bucket creation and policies)
  minio-client:
    image: minio/mc:latest
    container_name: minio-client-airflow
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: >
      sh -c "
        sleep 10 &&
        mc alias set myminio http://minio:9000 minioadmin minioadmin &&
        mc mb myminio/spark-data || true &&
        mc mb myminio/spark-output || true &&
        mc mb myminio/spark-checkpoints || true &&
        mc policy set public myminio/spark-data || true &&
        mc policy set public myminio/spark-output || true &&
        mc policy set public myminio/spark-checkpoints || true &&
        echo 'MinIO setup completed'
      "
    networks:
      - spark-network

  # Spark Master
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-master
    depends_on:
      - minio
      - minio-client
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - STORAGE_ENDPOINT=http://minio:9000
      - STORAGE_ACCESS_KEY_ID=minioadmin
      - STORAGE_SECRET_KEY=minioadmin
      - STORAGE_BUCKET=spark-data
    ports:
      - "8081:8080"  # Spark Master UI (8080 inside container)
      - "7077:7077"  # Spark Master RPC
    volumes:
      - ./data:/app/data:ro
      - ./output:/app/output
      - spark_logs:/opt/spark/logs
      - spark_work:/opt/spark/work
    networks:
      - spark-network
    restart: unless-stopped
    command: >
      sh -c "
        sleep 15 &&
        /opt/spark/sbin/start-master.sh &&
        tail -f /opt/spark/logs/spark-*-org.apache.spark.deploy.master.Master-*.out
      "

  # Spark Worker 1
  spark-worker-1:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-worker-1
    depends_on:
      - spark-master
      - minio
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - STORAGE_ENDPOINT=http://minio:9000
      - STORAGE_ACCESS_KEY_ID=minioadmin
      - STORAGE_SECRET_KEY=minioadmin
    volumes:
      - ./data:/app/data:ro
      - ./output:/app/output
      - spark_logs:/opt/spark/logs
      - spark_work:/opt/spark/work
    networks:
      - spark-network
    restart: unless-stopped
    command: >
      sh -c "
        sleep 20 &&
        /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
        tail -f /opt/spark/logs/spark-*-org.apache.spark.deploy.worker.Worker-*.out
      "

  # Spark Worker 2
  spark-worker-2:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-worker-2
    depends_on:
      - spark-master
      - minio
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - STORAGE_ENDPOINT=http://minio:9000
      - STORAGE_ACCESS_KEY_ID=minioadmin
      - STORAGE_SECRET_KEY=minioadmin
    volumes:
      - ./data:/app/data:ro
      - ./output:/app/output
      - spark_logs:/opt/spark/logs
      - spark_work:/opt/spark/work
    networks:
      - spark-network
    restart: unless-stopped
    command: >
      sh -c "
        sleep 20 &&
        /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
        tail -f /opt/spark/logs/spark-*-org.apache.spark.deploy.worker.Worker-*.out
      "

  # Spark Worker 3
  spark-worker-3:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-worker-3
    depends_on:
      - spark-master
      - minio
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - STORAGE_ENDPOINT=http://minio:9000
      - STORAGE_ACCESS_KEY_ID=minioadmin
      - STORAGE_SECRET_KEY=minioadmin
    volumes:
      - ./data:/app/data:ro
      - ./output:/app/output
      - spark_logs:/opt/spark/logs
      - spark_work:/opt/spark/work
    networks:
      - spark-network
    restart: unless-stopped
    command: >
      sh -c "
        sleep 20 &&
        /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
        tail -f /opt/spark/logs/spark-*-org.apache.spark.deploy.worker.Worker-*.out
      "



volumes:
  postgres-db-volume:
  minio-data:
  spark_logs:
  spark_work:

networks:
  spark-network:
