apiVersion: v1
kind: Pod
metadata:
  name: "dbt-pod-template"
spec:
  securityContext:
    runAsUser: 185
    runAsGroup: 185
    fsGroup: 185
  containers:
    - name: dbt-pod
      imagePullPolicy: IfNotPresent
      env:
        - name: SPARK_DRIVER_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DBT_STANDALONE
          value: "false"
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1"
  restartPolicy: Never
