apiVersion: v1
kind: Pod
metadata:
  name: spark-executor-minimal
  labels:
    spark-role: executor
spec:
  securityContext:
    runAsUser: 185
    runAsGroup: 185
    fsGroup: 185
  serviceAccountName: airflow-worker
  restartPolicy: Never
  containers:
    - name: spark-kubernetes
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1"