[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sparks"
version = "0.0.1"

[tool.setuptools.packages]
find = {}  # Scan the project directory with the default parameters